CUDA_VISIBLE_DEVICES=6 \
torchrun --nproc_per_node=2 --master_port 18340 train_downstream.py \
    --Train_csv_path '/home/user/KHJ/PMC-VQA/PMC-VQA/train.csv' \
    --Eval_csv_path '/home/user/KHJ/PMC-VQA/PMC-VQA/valid.csv' \
    --output_dir ./Results/QA_no_pretrain_no_aug \
    --run_name QA_no_pretrain_no_aug \
    --num_train_epochs 100 \
    --per_device_train_batch_size 8 \
    --per_device_eval_batch_size 8 \
    --gradient_accumulation_steps 1 \
    --evaluation_strategy "epoch" \
    --save_strategy "epoch" \
    --load_best_model_at_end True \
    --save_total_limit 2 \
    --learning_rate 2e-5 \
    --weight_decay 0. \
    --warmup_ratio 0.03 \
    --lr_scheduler_type "cosine" \
    --logging_steps 1 \
    --deepspeed ./ds_config/ds_config_zero2.json \
    --checkpointing false \
    --bf16 True \
    --tf32 True
